--// Create Schema

CREATE TABLE PRODUCTS
(
    PRODUCT_ID            NUMBER(10) NOT NULL ,
    PRODUCT_NAME          VARCHAR2(128) NULL ,
    PRODUCT_CATEGORY      VARCHAR2(128) NULL ,
    PRODUCT_DESC          VARCHAR2(1024) NULL ,
    PRODUCT_PRICE         NUMBER(10) NULL ,
CONSTRAINT PRODUCT_ID_PK PRIMARY KEY (PRODUCT_ID)
)/

CREATE TABLE USERS
(
    USERNAME              VARCHAR2(32) NOT NULL ,
    PASSWORD              VARCHAR2(32) NOT NULL ,
CONSTRAINT USERNAME_PK PRIMARY KEY (USERNAME)
)/

--//@UNDO

