insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('iPhone 5S','Smartphone','High tech phone',400);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Sony Z4','Smartphone','High tech phone',500);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('HTC One M9','Smartphone','High tech phone',600);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Samsung Galaxy S6','Smartphone','High tech phone',800);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('MSI GT70','Laptop','High tech PC',200);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Asus G55','Laptop','High tech PC',300);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('HP 8770W','Laptop','High tech PC',400);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Alienware M18X','Laptop','High tech PC',600);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Wave @','Motorbike','Consumer bike',600);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Exciter 150','Motorbike','Consumer bike',700);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Vespa','Motorbike','Consumer bike',900);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Hayate','Motorbike','Consumer bike',2000);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Logitech G700s','Mouse','Gamer mice',500);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Razer Mamba 4G','Mouse','Gamer mice',700);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('SteelSeries Sensei','Mouse','Gamer mice',750);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Roccat Kone+','Mouse','Gamer mice',850);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Sony XB950','Headphone','Audiophile headphone',250);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Koss Potapro','Headphone','Audiophile headphone',150);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('HIFIMAN HE-400','Headphone','Audiophile headphone',450);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('AKG Q701','Headphone','Audiophile headphone',700);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Sony Walkman','Music Player','Portable music player',200);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('iPod','Music Player','Portable music player',220);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Sansa Clip','Music Player','Portable music player',210);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('FiiO X10','Music Player','Portable music player',400);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Bugatti Veyron Supersport','Supercar','Very fast and expensive car',4000);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Pagani Zonda Cinque Roadster','Supercar','Very fast and expensive car',5000);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Lamborghini Reventon','Supercar','Very fast and expensive car',4500);
insert into PRODUCTS(product_name,product_category,product_desc,product_price) values('Lykan hypersport','Supercar','Very fast and expensive car',8000);